// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import Navbar from './components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <SignedIn>
        <html lang='en' suppressHydrationWarning>
          <body className={inter.className}>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
              <Providers>
                <Navbar />
                {children}
              </Providers>
            </ThemeProvider>
          </body>
        </html>
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </ClerkProvider>
  )
}
