// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import Navbar from './components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { CartProvider } from './context/CartContext'
import { Suspense } from 'react'
import Loading from './loading'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopwise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <CartProvider>
              <Navbar />
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </CartProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
