import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from './components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { CartProvider } from './context/CartContext'
import { Suspense } from 'react'
import Loading from './loading'

import { SiteFooter } from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopwise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${inter.className} h-screen dark:bg-gradient-to-r dark:from-[#0F172A] dark:to-[#17233f]  bg-gradient-to-r from-slate-100 to-[#d4e7ff] `}
        >
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <CartProvider>
              <Navbar />
              <Suspense fallback={<Loading />}>{children}</Suspense>
              <SiteFooter />
            </CartProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
